/* Consigna 1 */
SELECT
    CARRIER AS Carrier,
    DATEPART(YEAR, TRY_CONVERT(DATE, DELIVER_DATE, 1)) AS Year,
    DATEPART(QUARTER, TRY_CONVERT(DATE, DELIVER_DATE, 1)) AS Quarter,
    COUNT(DISTINCT SHIPMENT_ID) AS Total_Shipments,
    ROUND(SUM(TRY_CAST(REPLACE(WEIGHT_KG, ',', '') AS FLOAT)), 2) AS Total_Weight_KG
FROM dbo.Details
WHERE SHIPMENT_ID IS NOT NULL
  AND DELIVER_DATE IS NOT NULL
GROUP BY
    CARRIER,
    DATEPART(YEAR, TRY_CONVERT(DATE, DELIVER_DATE, 1)),
    DATEPART(QUARTER, TRY_CONVERT(DATE, DELIVER_DATE, 1))
ORDER BY Total_Weight_KG DESC;
GO


/* Consigna 2 */
SELECT
    ROUND(AVG(CAST(DATEDIFF(
        DAY,
        TRY_CONVERT(DATE, COLLECT_DATE, 1),
        TRY_CONVERT(DATE, DELIVER_DATE, 1)
    ) AS FLOAT)), 2) AS Avg_Delivery_Days
FROM dbo.Details
WHERE SHIPMENT_ID IS NOT NULL
  AND COLLECT_DATE IS NOT NULL
  AND DELIVER_DATE IS NOT NULL;
GO


/* Consigna 3 */
SELECT TOP 10
    FROM_PCODE AS Origin_Pcode,
    TO_PCODE AS Destination_Pcode,
    FROM_CITY AS Origin_City,
    TO_CITY AS Destination_City,
    COUNT(DISTINCT SHIPMENT_ID) AS Total_Shipments,
    ROUND(SUM(TRY_CAST(REPLACE(VOLUME_M3, ',', '') AS FLOAT)), 2) AS Total_Volume_M3
FROM dbo.Details
WHERE SHIPMENT_ID IS NOT NULL
GROUP BY
    FROM_PCODE,
    TO_PCODE,
    FROM_CITY,
    TO_CITY
ORDER BY Total_Volume_M3 DESC;
GO


/* Consigna 4 */
SELECT
    DATEPART(YEAR, TRY_CONVERT(DATE, DELIVER_DATE, 1)) AS Year,
    DATEPART(WEEK, TRY_CONVERT(DATE, DELIVER_DATE, 1)) AS Week,
    COUNT(DISTINCT SHIPMENT_ID) AS Total_Shipments
FROM dbo.Details
WHERE SHIPMENT_ID IS NOT NULL
  AND DELIVER_DATE IS NOT NULL
GROUP BY
    DATEPART(YEAR, TRY_CONVERT(DATE, DELIVER_DATE, 1)),
    DATEPART(WEEK, TRY_CONVERT(DATE, DELIVER_DATE, 1))
ORDER BY
    Year,
    Week;
GO


/* Consigna 5 */
SELECT
    CASE
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 50 THEN '0-50 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 500 THEN '50-500 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 1000 THEN '500-1000 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 5000 THEN '1000-5000 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 10000 THEN '5000-10000 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 20000 THEN '10000-20000 Kg'
        ELSE 'Above 20000 Kg'
    END AS Weight_Bracket,
    COUNT(DISTINCT SHIPMENT_ID) AS Shipment_Count
FROM dbo.Details
WHERE SHIPMENT_ID IS NOT NULL
  AND TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) IS NOT NULL
GROUP BY
    CASE
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 50 THEN '0-50 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 500 THEN '50-500 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 1000 THEN '500-1000 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 5000 THEN '1000-5000 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 10000 THEN '5000-10000 Kg'
        WHEN TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT) <= 20000 THEN '10000-20000 Kg'
        ELSE 'Above 20000 Kg'
    END
ORDER BY
    MIN(TRY_CAST(REPLACE(CHARGEABLE_WEIGHT, ',', '') AS FLOAT));
GO